# syntax=docker/dockerfile:1.7
FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod ./
# go.sum is generated by go mod download when missing; no pre-committed file required.
RUN go mod download
COPY . .
# Regenerate go.sum from the vendored download cache so build steps are reproducible.
RUN go mod tidy

FROM builder AS bot-builder
RUN CGO_ENABLED=0 go build -trimpath -o /bin/bot ./cmd/bot

FROM builder AS watchdog-builder
RUN CGO_ENABLED=0 go build -trimpath -o /bin/watchdog ./cmd/watchdog

# ── Final images (distroless for minimal attack surface) ──────────────────────
FROM gcr.io/distroless/static:nonroot AS bot
COPY --from=bot-builder /bin/bot /bot
ENTRYPOINT ["/bot"]

FROM gcr.io/distroless/static:nonroot AS watchdog
COPY --from=watchdog-builder /bin/watchdog /watchdog
ENTRYPOINT ["/watchdog"]
